name: CI

on: [ push, pull_request ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Standard
        uses: goto-bus-stop/standard-action@v1
        with:
          annotate: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  build:
    name: Docker
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and publish to registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: switchbladebot/switchblade-legacy
          tag_with_ref: true