name: Standard

on: [push, pull_request]
    
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/standard-action@v1
        with:
          annotate: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
